// Code generated by mockery 2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ProjectHelper is an autogenerated mock type for the ProjectHelper type
type ProjectHelper struct {
	mock.Mock
}

// IsSigningManagedAutomatically provides a mock function with given fields:
func (_m *ProjectHelper) IsSigningManagedAutomatically() (bool, error) {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
